dataset: exchange
fixed:
  root_path: ./datasets/
  data_path: Exchange.csv
  model: DACNet_In
  model_id: Exchange
  data: custom
  enc_in: 8
  cycle: 1
  learning_rate: 0.005
  lradj: type4
  sim_mode: l1
  mix: 0
  seq_len: 96
  backbone: mlp
pred_len_configs:
  96:
    use_norm: 2
    D_cp: 16
    D_de: 16
    D_mix: 8
    d_model: 512
  192:
    use_norm: 2
    D_cp: 16
    D_de: 16
    D_mix: 8
    d_model: 512
  336:
    use_norm: 2
    D_cp: 16
    D_de: 16
    D_mix: 8
    d_model: 512
  720:
    use_norm: 2
    D_cp: 16
    D_de: 16
    D_mix: 8
    d_model: 512